# Generated by Django 2.2.1 on 2020-06-26 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_recommendations_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyRating',
        ),
    ]
