# Generated by Django 2.2.1 on 2020-06-29 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_recommendations_app', '0005_auto_20200628_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='logo',
            field=models.URLField(blank=True, default='https://thumbs.dreamstime.com/z/cinema-art-movie-watching-industry-symbols-icons-isolated-white-background-vector-illustration-107286831.jpg'),
        ),
    ]
