# Generated by Django 2.2.1 on 2020-07-06 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_recommendations_app', '0006_movie_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myrating',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='myrating',
            name='user',
        ),
        migrations.DeleteModel(
            name='Movie',
        ),
        migrations.DeleteModel(
            name='MyRating',
        ),
    ]
